<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>netHEmusic_Setup_26.9.12.22</AssemblyName>
    <ApplicationIcon>..\..\resources\icon.ico</ApplicationIcon>
    <Version>26.9.12.22</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\build\netHEmusic-26.9.12.22.zip" LogicalName="app.zip" />
    <EmbeddedResource Include="..\..\build\LaoheTeam.cer" LogicalName="LaoheTeam.cer" />
  </ItemGroup>
</Project>
